CREATE TYPE "public"."follow_entity_type" AS ENUM('player', 'team', 'league', 'competition', 'partner');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('user', 'editor', 'admin', 'partner');--> statement-breakpoint
CREATE TYPE "public"."partner_status" AS ENUM('pending', 'approved', 'rejected', 'suspended', 'active');--> statement-breakpoint
CREATE TYPE "public"."campaign_status" AS ENUM('draft', 'active', 'paused', 'completed', 'archived');--> statement-breakpoint
CREATE TYPE "public"."content_label_type" AS ENUM('sponsored', 'promoted', 'premium', 'campaign', 'partner_promo', 'house_ad', 'affiliate', 'featured_sponsor');--> statement-breakpoint
CREATE TABLE "analytics_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"event_type" text NOT NULL,
	"path" text NOT NULL,
	"article_id" integer,
	"referrer" text,
	"user_agent" text,
	"session_id" text,
	"partner_id" integer,
	"referral_code" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bookmarks" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"news_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "comments" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"news_id" integer NOT NULL,
	"parent_id" integer,
	"body" text NOT NULL,
	"author_name" text NOT NULL,
	"author_email" text NOT NULL,
	"reported" boolean DEFAULT false NOT NULL,
	"report_reason" text,
	"approved" boolean DEFAULT true NOT NULL,
	"removed" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "entity_follows" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"entity_type" "follow_entity_type" NOT NULL,
	"entity_id" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "competitions" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"country" text,
	"sport" text DEFAULT 'football' NOT NULL,
	"logo_url" text,
	"api_id" text,
	"is_demo" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "competitions_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "fixtures" (
	"id" serial PRIMARY KEY NOT NULL,
	"competition_id" integer,
	"home_team_id" integer,
	"away_team_id" integer,
	"home_score" integer,
	"away_score" integer,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"match_date" timestamp with time zone NOT NULL,
	"venue" text,
	"stage" text,
	"round" text,
	"api_id" text,
	"last_synced_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "teams" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"short_name" text,
	"logo_url" text,
	"sport" text DEFAULT 'football' NOT NULL,
	"api_id" text,
	"is_demo" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "teams_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "audit_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"event_id" uuid NOT NULL,
	"correlation_id" uuid NOT NULL,
	"event_type" text NOT NULL,
	"event_version" integer DEFAULT 1 NOT NULL,
	"timestamp" timestamp with time zone NOT NULL,
	"server_timestamp" timestamp with time zone NOT NULL,
	"actor_type" text DEFAULT 'anonymous' NOT NULL,
	"actor_id" integer,
	"actor_id_type" text,
	"session_id" text,
	"http_method" text,
	"http_path" text,
	"http_status" integer,
	"client_ip_hash" text NOT NULL,
	"client_ip_country" text,
	"client_ip_asn" integer,
	"client_ip_is_dc" boolean DEFAULT false,
	"user_agent_hash" text,
	"user_agent_engine" text,
	"user_agent_os" text,
	"user_agent_is_bot" boolean DEFAULT false,
	"ja3_hash" text,
	"header_order_hash" text,
	"h2_settings_hash" text,
	"fraud_score" integer DEFAULT 0 NOT NULL,
	"fraud_verdict" text DEFAULT 'clean' NOT NULL,
	"fraud_reasons" jsonb DEFAULT '[]' NOT NULL,
	"previous_hash" text NOT NULL,
	"row_hash" text NOT NULL,
	"payload" jsonb DEFAULT '{}' NOT NULL,
	"created_date" date NOT NULL,
	CONSTRAINT "audit_events_event_id_unique" UNIQUE("event_id")
);
--> statement-breakpoint
CREATE TABLE "detection_alerts" (
	"id" serial PRIMARY KEY NOT NULL,
	"alert_id" uuid NOT NULL,
	"tier" text NOT NULL,
	"status" text DEFAULT 'pending_review' NOT NULL,
	"rule_ids" jsonb NOT NULL,
	"partner_id" integer,
	"summary" text NOT NULL,
	"evidence" jsonb NOT NULL,
	"fraud_score_avg" integer,
	"affected_events" integer,
	"assigned_to" text,
	"assigned_at" timestamp with time zone,
	"resolution" text,
	"resolution_notes" text,
	"resolved_at" timestamp with time zone,
	"resolved_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "detection_alerts_alert_id_unique" UNIQUE("alert_id")
);
--> statement-breakpoint
CREATE TABLE "publisher_risk_scores" (
	"partner_id" integer PRIMARY KEY NOT NULL,
	"risk_score" integer DEFAULT 0 NOT NULL,
	"click_velocity_score" integer DEFAULT 0 NOT NULL,
	"bot_signal_score" integer DEFAULT 0 NOT NULL,
	"conversion_anomaly_score" integer DEFAULT 0 NOT NULL,
	"geo_anomaly_score" integer DEFAULT 0 NOT NULL,
	"behavioral_score" integer DEFAULT 0 NOT NULL,
	"clicks_24h" integer DEFAULT 0 NOT NULL,
	"clicks_7d" integer DEFAULT 0 NOT NULL,
	"unique_ips_24h" integer DEFAULT 0 NOT NULL,
	"unique_fingerprints_24h" integer DEFAULT 0 NOT NULL,
	"flagged_click_pct_24h" numeric(5, 2) DEFAULT '0' NOT NULL,
	"conversion_rate_7d" numeric(5, 4) DEFAULT '0' NOT NULL,
	"mean_clicks_per_hour_30d" numeric(10, 2),
	"stddev_clicks_per_hour_30d" numeric(10, 2),
	"mean_unique_ips_per_hour_30d" numeric(10, 2),
	"status" text DEFAULT 'normal' NOT NULL,
	"watchlist_reason" text,
	"suspended_at" timestamp with time zone,
	"suspended_by" text,
	"last_evaluated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "news" (
	"id" serial PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"body" text,
	"image" text NOT NULL,
	"category" text NOT NULL,
	"language" text NOT NULL,
	"source" text NOT NULL,
	"author" text NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"slug" text,
	"reading_time" integer,
	"meta_title" text,
	"meta_description" text,
	"publication_date" timestamp with time zone NOT NULL,
	"featured" boolean DEFAULT false NOT NULL,
	"published" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"partner_id" integer,
	"review_note" text,
	"reviewed_by" integer,
	"reviewed_at" timestamp with time zone,
	"is_sponsored" boolean DEFAULT false NOT NULL,
	"sponsor_name" text,
	"sponsor_url" text,
	"content_type" text DEFAULT 'editorial' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "newsletter_subscribers" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"role" "user_role" DEFAULT 'user' NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"referred_by_partner_id" integer,
	"referred_by_code" text,
	"mfa_secret" text,
	"mfa_enabled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_sessions" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"token_hash" text NOT NULL,
	"purpose" text DEFAULT 'login' NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "push_subscriptions" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"endpoint" text NOT NULL,
	"p256dh" text NOT NULL,
	"auth" text NOT NULL,
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "password_resets" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"token_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notification_preferences" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"new_articles" boolean DEFAULT true NOT NULL,
	"important_news" boolean DEFAULT true NOT NULL,
	"weekly_digest" boolean DEFAULT false NOT NULL,
	"email_notifications" boolean DEFAULT false NOT NULL,
	"push_notifications" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "notification_preferences_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"type" text DEFAULT 'info' NOT NULL,
	"title" text NOT NULL,
	"message" text NOT NULL,
	"link" text,
	"read" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"action" text NOT NULL,
	"target_type" text,
	"target_id" integer,
	"details" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "moderation_reports" (
	"id" serial PRIMARY KEY NOT NULL,
	"reporter_id" integer,
	"target_type" text NOT NULL,
	"target_id" integer NOT NULL,
	"reason" text NOT NULL,
	"details" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"reviewed_by" integer,
	"reviewed_at" timestamp with time zone,
	"resolution" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "imported_articles" (
	"id" serial PRIMARY KEY NOT NULL,
	"source_name" text NOT NULL,
	"original_url" text NOT NULL,
	"title" text NOT NULL,
	"summary" text,
	"original_content" text,
	"author" text,
	"category" text,
	"tags" text[] DEFAULT '{}',
	"image_url" text,
	"publication_date" timestamp with time zone,
	"status" text DEFAULT 'pending' NOT NULL,
	"news_id" integer,
	"imported_by" text,
	"error_message" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "imported_articles_original_url_unique" UNIQUE("original_url")
);
--> statement-breakpoint
CREATE TABLE "sports_data_cache" (
	"id" serial PRIMARY KEY NOT NULL,
	"cache_key" text NOT NULL,
	"data" jsonb NOT NULL,
	"provider" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sports_data_cache_cache_key_unique" UNIQUE("cache_key")
);
--> statement-breakpoint
CREATE TABLE "players" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"nationality" text,
	"date_of_birth" timestamp with time zone,
	"position" text,
	"club" text,
	"club_id" integer,
	"shirt_number" integer,
	"photo_url" text,
	"biography" text,
	"goals" integer DEFAULT 0 NOT NULL,
	"assists" integer DEFAULT 0 NOT NULL,
	"appearances" integer DEFAULT 0 NOT NULL,
	"minutes" integer DEFAULT 0 NOT NULL,
	"yellow_cards" integer DEFAULT 0 NOT NULL,
	"red_cards" integer DEFAULT 0 NOT NULL,
	"trophies" text[] DEFAULT '{}' NOT NULL,
	"api_id" text,
	"is_demo" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "players_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "match_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"match_id" integer NOT NULL,
	"event_type" text NOT NULL,
	"minute" integer,
	"player_id" integer,
	"player_name" text,
	"related_player_id" integer,
	"related_player_name" text,
	"team_side" text,
	"detail" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "match_lineups" (
	"id" serial PRIMARY KEY NOT NULL,
	"match_id" integer NOT NULL,
	"team_side" text NOT NULL,
	"formation" text,
	"lineup" jsonb
);
--> statement-breakpoint
CREATE TABLE "match_statistics" (
	"id" serial PRIMARY KEY NOT NULL,
	"match_id" integer NOT NULL,
	"possession" jsonb,
	"shots" jsonb,
	"shots_on_target" jsonb,
	"corners" jsonb,
	"fouls" jsonb,
	"offsides" jsonb,
	"yellow_cards" jsonb,
	"red_cards" jsonb,
	"saves" jsonb,
	CONSTRAINT "match_statistics_match_id_unique" UNIQUE("match_id")
);
--> statement-breakpoint
CREATE TABLE "matches" (
	"id" serial PRIMARY KEY NOT NULL,
	"competition_id" integer,
	"home_team_id" integer,
	"away_team_id" integer,
	"home_team_name" text NOT NULL,
	"away_team_name" text NOT NULL,
	"home_team_logo" text,
	"away_team_logo" text,
	"home_score" integer DEFAULT 0,
	"away_score" integer DEFAULT 0,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"minute" integer,
	"match_date" timestamp with time zone NOT NULL,
	"venue" text,
	"competition_name" text,
	"competition_logo" text,
	"api_id" text,
	"is_demo" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "transfers" (
	"id" serial PRIMARY KEY NOT NULL,
	"player_name" text NOT NULL,
	"player_id" integer,
	"from_club" text NOT NULL,
	"to_club" text NOT NULL,
	"fee" text,
	"status" text DEFAULT 'rumour' NOT NULL,
	"transfer_type" text DEFAULT 'permanent',
	"transfer_date" timestamp with time zone,
	"source" text,
	"confidence" integer DEFAULT 50,
	"api_id" text,
	"is_demo" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "leaderboard" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"username" text NOT NULL,
	"total_points" integer DEFAULT 0 NOT NULL,
	"correct_predictions" integer DEFAULT 0 NOT NULL,
	"total_predictions" integer DEFAULT 0 NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "leaderboard_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
CREATE TABLE "predictions" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"match_id" integer NOT NULL,
	"prediction" text NOT NULL,
	"home_score_pred" integer,
	"away_score_pred" integer,
	"points" integer DEFAULT 0,
	"result" text,
	"is_demo" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "predictions_user_match_idx" UNIQUE("user_id","match_id")
);
--> statement-breakpoint
CREATE TABLE "team_pages" (
	"id" serial PRIMARY KEY NOT NULL,
	"team_id" integer,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"short_name" text,
	"country" text NOT NULL,
	"league" text NOT NULL,
	"badge" text,
	"description" text,
	"founded" integer,
	"stadium" text,
	"capacity" integer,
	"league_position" integer,
	"points" integer,
	"played" integer,
	"won" integer,
	"drawn" integer,
	"lost" integer,
	"goals_for" integer,
	"goals_against" integer,
	"form" text[],
	"api_id" text,
	"is_demo" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "team_pages_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "creator_earnings_ledger" (
	"id" serial PRIMARY KEY NOT NULL,
	"partner_id" integer NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"type" text DEFAULT 'click' NOT NULL,
	"description" text,
	"reference_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "partners" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"referral_code" text NOT NULL,
	"website" text,
	"social_handle" text,
	"status" "partner_status" DEFAULT 'pending' NOT NULL,
	"commission_rate" numeric(5, 2) DEFAULT '10.00' NOT NULL,
	"total_clicks" integer DEFAULT 0 NOT NULL,
	"total_earnings" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"paid_earnings" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"bio" text,
	"avatar" text,
	"facebook" text,
	"instagram" text,
	"tiktok" text,
	"youtube" text,
	"phone" text,
	"address" text,
	"approved_at" timestamp with time zone,
	"approved_by" integer,
	"rejected_at" timestamp with time zone,
	"rejected_by" integer,
	"rejected_reason" text,
	"suspended_at" timestamp with time zone,
	"suspended_by" integer,
	"suspended_reason" text,
	"secret_hash" text,
	"secret_prefix" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payouts" (
	"id" serial PRIMARY KEY NOT NULL,
	"partner_id" integer NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"method" text DEFAULT 'manual' NOT NULL,
	"reference" text,
	"notes" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"idempotency_key" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "referral_clicks" (
	"id" serial PRIMARY KEY NOT NULL,
	"partner_id" integer NOT NULL,
	"link_id" integer,
	"code" text NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"referer" text,
	"fingerprint" text,
	"target_url" text,
	"utm_source" text,
	"utm_medium" text,
	"utm_campaign" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "referral_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"partner_id" integer NOT NULL,
	"link_id" integer,
	"event_type" text DEFAULT 'click' NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"referer" text,
	"target_url" text,
	"metadata" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "referral_links" (
	"id" serial PRIMARY KEY NOT NULL,
	"partner_id" integer NOT NULL,
	"code" text NOT NULL,
	"target_url" text NOT NULL,
	"label" text,
	"active" boolean DEFAULT true NOT NULL,
	"click_count" integer DEFAULT 0 NOT NULL,
	"utm_source" text,
	"utm_medium" text,
	"utm_campaign" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ad_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"ad_id" integer,
	"event_type" text NOT NULL,
	"session_id" text,
	"partner_id" integer,
	"campaign_id" integer,
	"article_id" integer,
	"user_agent" text,
	"ip_address" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ad_placements" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"slot" text,
	"location" text NOT NULL,
	"ad_type" text DEFAULT 'display' NOT NULL,
	"priority" integer DEFAULT 0 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"width" integer,
	"height" integer,
	"target_url" text,
	"image_url" text,
	"alt_text" text,
	"impressions" integer DEFAULT 0 NOT NULL,
	"clicks" integer DEFAULT 0 NOT NULL,
	"partner_id" integer,
	"campaign_id" integer,
	"starts_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"created_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "campaigns" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"type" text DEFAULT 'partner' NOT NULL,
	"status" "campaign_status" DEFAULT 'draft' NOT NULL,
	"partner_id" integer,
	"budget" numeric(12, 2),
	"spend" numeric(12, 2) DEFAULT '0.00' NOT NULL,
	"target_impressions" integer,
	"actual_impressions" integer DEFAULT 0 NOT NULL,
	"target_clicks" integer,
	"actual_clicks" integer DEFAULT 0 NOT NULL,
	"starts_at" timestamp with time zone,
	"ends_at" timestamp with time zone,
	"metadata" json,
	"created_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "content_labels" (
	"id" serial PRIMARY KEY NOT NULL,
	"news_id" integer,
	"label_type" "content_label_type" NOT NULL,
	"label" text,
	"url" text,
	"metadata" json,
	"starts_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"active" boolean DEFAULT true NOT NULL,
	"partner_id" integer,
	"campaign_id" integer,
	"created_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monetization_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"event_type" text NOT NULL,
	"article_id" integer,
	"ad_id" integer,
	"partner_id" integer,
	"campaign_id" integer,
	"session_id" text,
	"metadata" json,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "analytics_events" ADD CONSTRAINT "analytics_events_article_id_news_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."news"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "analytics_events" ADD CONSTRAINT "analytics_events_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookmarks" ADD CONSTRAINT "bookmarks_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bookmarks" ADD CONSTRAINT "bookmarks_news_id_news_id_fk" FOREIGN KEY ("news_id") REFERENCES "public"."news"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_news_id_news_id_fk" FOREIGN KEY ("news_id") REFERENCES "public"."news"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comments" ADD CONSTRAINT "comments_parent_id_comments_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."comments"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "entity_follows" ADD CONSTRAINT "entity_follows_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fixtures" ADD CONSTRAINT "fixtures_competition_id_competitions_id_fk" FOREIGN KEY ("competition_id") REFERENCES "public"."competitions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fixtures" ADD CONSTRAINT "fixtures_home_team_id_teams_id_fk" FOREIGN KEY ("home_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "fixtures" ADD CONSTRAINT "fixtures_away_team_id_teams_id_fk" FOREIGN KEY ("away_team_id") REFERENCES "public"."teams"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "detection_alerts" ADD CONSTRAINT "detection_alerts_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "publisher_risk_scores" ADD CONSTRAINT "publisher_risk_scores_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "news" ADD CONSTRAINT "news_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "news" ADD CONSTRAINT "news_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "push_subscriptions" ADD CONSTRAINT "push_subscriptions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "password_resets" ADD CONSTRAINT "password_resets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notification_preferences" ADD CONSTRAINT "notification_preferences_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "moderation_reports" ADD CONSTRAINT "moderation_reports_reporter_id_users_id_fk" FOREIGN KEY ("reporter_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "moderation_reports" ADD CONSTRAINT "moderation_reports_reviewed_by_users_id_fk" FOREIGN KEY ("reviewed_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "imported_articles" ADD CONSTRAINT "imported_articles_news_id_news_id_fk" FOREIGN KEY ("news_id") REFERENCES "public"."news"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "players" ADD CONSTRAINT "players_club_id_teams_id_fk" FOREIGN KEY ("club_id") REFERENCES "public"."teams"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "match_events" ADD CONSTRAINT "match_events_match_id_matches_id_fk" FOREIGN KEY ("match_id") REFERENCES "public"."matches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "match_lineups" ADD CONSTRAINT "match_lineups_match_id_matches_id_fk" FOREIGN KEY ("match_id") REFERENCES "public"."matches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "match_statistics" ADD CONSTRAINT "match_statistics_match_id_matches_id_fk" FOREIGN KEY ("match_id") REFERENCES "public"."matches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matches" ADD CONSTRAINT "matches_competition_id_competitions_id_fk" FOREIGN KEY ("competition_id") REFERENCES "public"."competitions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matches" ADD CONSTRAINT "matches_home_team_id_teams_id_fk" FOREIGN KEY ("home_team_id") REFERENCES "public"."teams"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "matches" ADD CONSTRAINT "matches_away_team_id_teams_id_fk" FOREIGN KEY ("away_team_id") REFERENCES "public"."teams"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "predictions" ADD CONSTRAINT "predictions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "predictions" ADD CONSTRAINT "predictions_match_id_matches_id_fk" FOREIGN KEY ("match_id") REFERENCES "public"."matches"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "team_pages" ADD CONSTRAINT "team_pages_team_id_teams_id_fk" FOREIGN KEY ("team_id") REFERENCES "public"."teams"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "creator_earnings_ledger" ADD CONSTRAINT "creator_earnings_ledger_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "partners" ADD CONSTRAINT "partners_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "partners" ADD CONSTRAINT "partners_approved_by_users_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "partners" ADD CONSTRAINT "partners_rejected_by_users_id_fk" FOREIGN KEY ("rejected_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "partners" ADD CONSTRAINT "partners_suspended_by_users_id_fk" FOREIGN KEY ("suspended_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payouts" ADD CONSTRAINT "payouts_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "referral_clicks" ADD CONSTRAINT "referral_clicks_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "referral_clicks" ADD CONSTRAINT "referral_clicks_link_id_referral_links_id_fk" FOREIGN KEY ("link_id") REFERENCES "public"."referral_links"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "referral_events" ADD CONSTRAINT "referral_events_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "referral_events" ADD CONSTRAINT "referral_events_link_id_referral_links_id_fk" FOREIGN KEY ("link_id") REFERENCES "public"."referral_links"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "referral_links" ADD CONSTRAINT "referral_links_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ad_events" ADD CONSTRAINT "ad_events_ad_id_ad_placements_id_fk" FOREIGN KEY ("ad_id") REFERENCES "public"."ad_placements"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ad_events" ADD CONSTRAINT "ad_events_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ad_events" ADD CONSTRAINT "ad_events_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ad_events" ADD CONSTRAINT "ad_events_article_id_news_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."news"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ad_placements" ADD CONSTRAINT "ad_placements_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ad_placements" ADD CONSTRAINT "ad_placements_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "campaigns" ADD CONSTRAINT "campaigns_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_labels" ADD CONSTRAINT "content_labels_news_id_news_id_fk" FOREIGN KEY ("news_id") REFERENCES "public"."news"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_labels" ADD CONSTRAINT "content_labels_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_labels" ADD CONSTRAINT "content_labels_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "content_labels" ADD CONSTRAINT "content_labels_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monetization_events" ADD CONSTRAINT "monetization_events_article_id_news_id_fk" FOREIGN KEY ("article_id") REFERENCES "public"."news"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monetization_events" ADD CONSTRAINT "monetization_events_ad_id_ad_placements_id_fk" FOREIGN KEY ("ad_id") REFERENCES "public"."ad_placements"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monetization_events" ADD CONSTRAINT "monetization_events_partner_id_partners_id_fk" FOREIGN KEY ("partner_id") REFERENCES "public"."partners"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monetization_events" ADD CONSTRAINT "monetization_events_campaign_id_campaigns_id_fk" FOREIGN KEY ("campaign_id") REFERENCES "public"."campaigns"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "analytics_events_created_at_idx" ON "analytics_events" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "analytics_events_event_type_idx" ON "analytics_events" USING btree ("event_type");--> statement-breakpoint
CREATE INDEX "analytics_events_article_id_idx" ON "analytics_events" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX "analytics_events_partner_id_idx" ON "analytics_events" USING btree ("partner_id");--> statement-breakpoint
CREATE UNIQUE INDEX "bookmarks_user_news_idx" ON "bookmarks" USING btree ("user_id","news_id");--> statement-breakpoint
CREATE INDEX "bookmarks_user_id_idx" ON "bookmarks" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "comments_news_id_idx" ON "comments" USING btree ("news_id");--> statement-breakpoint
CREATE INDEX "comments_user_id_idx" ON "comments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "comments_approved_idx" ON "comments" USING btree ("approved");--> statement-breakpoint
CREATE INDEX "comments_reported_idx" ON "comments" USING btree ("reported");--> statement-breakpoint
CREATE INDEX "comments_parent_id_idx" ON "comments" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "entity_follows_user_id_idx" ON "entity_follows" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "entity_follows_entity_idx" ON "entity_follows" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "entity_follows_unique" ON "entity_follows" USING btree ("user_id","entity_type","entity_id");--> statement-breakpoint
CREATE UNIQUE INDEX "competitions_api_id_idx" ON "competitions" USING btree ("api_id");--> statement-breakpoint
CREATE INDEX "fixtures_match_date_idx" ON "fixtures" USING btree ("match_date");--> statement-breakpoint
CREATE INDEX "fixtures_status_idx" ON "fixtures" USING btree ("status");--> statement-breakpoint
CREATE INDEX "fixtures_competition_idx" ON "fixtures" USING btree ("competition_id");--> statement-breakpoint
CREATE UNIQUE INDEX "fixtures_api_id_idx" ON "fixtures" USING btree ("api_id");--> statement-breakpoint
CREATE UNIQUE INDEX "teams_api_id_idx" ON "teams" USING btree ("api_id");--> statement-breakpoint
CREATE INDEX "audit_events_timestamp_idx" ON "audit_events" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "audit_events_event_type_idx" ON "audit_events" USING btree ("event_type");--> statement-breakpoint
CREATE INDEX "audit_events_correlation_id_idx" ON "audit_events" USING btree ("correlation_id");--> statement-breakpoint
CREATE INDEX "audit_events_actor_idx" ON "audit_events" USING btree ("actor_id_type","actor_id");--> statement-breakpoint
CREATE INDEX "audit_events_client_ip_hash_idx" ON "audit_events" USING btree ("client_ip_hash");--> statement-breakpoint
CREATE INDEX "audit_events_fraud_verdict_idx" ON "audit_events" USING btree ("fraud_verdict") WHERE "audit_events"."fraud_verdict" != 'clean';--> statement-breakpoint
CREATE INDEX "audit_events_created_date_idx" ON "audit_events" USING btree ("created_date");--> statement-breakpoint
CREATE INDEX "detection_alerts_status_idx" ON "detection_alerts" USING btree ("status");--> statement-breakpoint
CREATE INDEX "detection_alerts_tier_idx" ON "detection_alerts" USING btree ("tier");--> statement-breakpoint
CREATE INDEX "detection_alerts_partner_id_idx" ON "detection_alerts" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "detection_alerts_created_at_idx" ON "detection_alerts" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "publisher_risk_scores_status_idx" ON "publisher_risk_scores" USING btree ("status");--> statement-breakpoint
CREATE INDEX "publisher_risk_scores_risk_score_idx" ON "publisher_risk_scores" USING btree ("risk_score" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "news_slug_idx" ON "news" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "news_category_idx" ON "news" USING btree ("category");--> statement-breakpoint
CREATE INDEX "news_published_idx" ON "news" USING btree ("published");--> statement-breakpoint
CREATE INDEX "news_status_idx" ON "news" USING btree ("status");--> statement-breakpoint
CREATE INDEX "news_partner_id_idx" ON "news" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "news_reviewed_by_idx" ON "news" USING btree ("reviewed_by");--> statement-breakpoint
CREATE INDEX "news_content_type_idx" ON "news" USING btree ("content_type");--> statement-breakpoint
CREATE INDEX "news_sponsored_idx" ON "news" USING btree ("is_sponsored");--> statement-breakpoint
CREATE UNIQUE INDEX "newsletter_subscribers_email_unique" ON "newsletter_subscribers" USING btree ("email");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_unique" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "user_sessions_token_hash_idx" ON "user_sessions" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "user_sessions_user_id_idx" ON "user_sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "push_subscriptions_endpoint_idx" ON "push_subscriptions" USING btree ("endpoint");--> statement-breakpoint
CREATE INDEX "push_subscriptions_user_id_idx" ON "push_subscriptions" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "push_subscriptions_endpoint_unique" ON "push_subscriptions" USING btree ("endpoint");--> statement-breakpoint
CREATE INDEX "password_resets_token_hash_idx" ON "password_resets" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX "password_resets_user_id_idx" ON "password_resets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "notifications_user_id_idx" ON "notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "notifications_read_idx" ON "notifications" USING btree ("read");--> statement-breakpoint
CREATE INDEX "audit_user_idx" ON "audit_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "audit_action_idx" ON "audit_log" USING btree ("action");--> statement-breakpoint
CREATE INDEX "moderation_status_idx" ON "moderation_reports" USING btree ("status");--> statement-breakpoint
CREATE INDEX "moderation_target_type_idx" ON "moderation_reports" USING btree ("target_type");--> statement-breakpoint
CREATE INDEX "moderation_reporter_idx" ON "moderation_reports" USING btree ("reporter_id");--> statement-breakpoint
CREATE INDEX "imported_articles_status_idx" ON "imported_articles" USING btree ("status");--> statement-breakpoint
CREATE INDEX "imported_articles_source_idx" ON "imported_articles" USING btree ("source_name");--> statement-breakpoint
CREATE INDEX "imported_articles_url_idx" ON "imported_articles" USING btree ("original_url");--> statement-breakpoint
CREATE INDEX "imported_articles_news_id_idx" ON "imported_articles" USING btree ("news_id");--> statement-breakpoint
CREATE INDEX "sports_cache_key_idx" ON "sports_data_cache" USING btree ("cache_key");--> statement-breakpoint
CREATE INDEX "sports_cache_expires_idx" ON "sports_data_cache" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "players_slug_idx" ON "players" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "players_club_idx" ON "players" USING btree ("club");--> statement-breakpoint
CREATE INDEX "players_club_id_idx" ON "players" USING btree ("club_id");--> statement-breakpoint
CREATE INDEX "players_name_idx" ON "players" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "players_api_id_idx" ON "players" USING btree ("api_id");--> statement-breakpoint
CREATE INDEX "match_events_match_idx" ON "match_events" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "match_lineups_match_idx" ON "match_lineups" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "matches_status_idx" ON "matches" USING btree ("status");--> statement-breakpoint
CREATE INDEX "matches_date_idx" ON "matches" USING btree ("match_date");--> statement-breakpoint
CREATE INDEX "matches_competition_idx" ON "matches" USING btree ("competition_id");--> statement-breakpoint
CREATE INDEX "matches_home_team_idx" ON "matches" USING btree ("home_team_id");--> statement-breakpoint
CREATE INDEX "matches_away_team_idx" ON "matches" USING btree ("away_team_id");--> statement-breakpoint
CREATE UNIQUE INDEX "matches_api_id_idx" ON "matches" USING btree ("api_id");--> statement-breakpoint
CREATE INDEX "transfers_status_idx" ON "transfers" USING btree ("status");--> statement-breakpoint
CREATE INDEX "transfers_player_idx" ON "transfers" USING btree ("player_name");--> statement-breakpoint
CREATE INDEX "transfers_club_idx" ON "transfers" USING btree ("to_club");--> statement-breakpoint
CREATE UNIQUE INDEX "transfers_api_id_idx" ON "transfers" USING btree ("api_id");--> statement-breakpoint
CREATE INDEX "leaderboard_points_idx" ON "leaderboard" USING btree ("total_points");--> statement-breakpoint
CREATE INDEX "predictions_user_idx" ON "predictions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "predictions_match_idx" ON "predictions" USING btree ("match_id");--> statement-breakpoint
CREATE INDEX "team_pages_slug_idx" ON "team_pages" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "team_pages_country_idx" ON "team_pages" USING btree ("country");--> statement-breakpoint
CREATE INDEX "team_pages_team_id_idx" ON "team_pages" USING btree ("team_id");--> statement-breakpoint
CREATE UNIQUE INDEX "team_pages_api_id_idx" ON "team_pages" USING btree ("api_id");--> statement-breakpoint
CREATE INDEX "earnings_ledger_partner_idx" ON "creator_earnings_ledger" USING btree ("partner_id");--> statement-breakpoint
CREATE UNIQUE INDEX "partners_referral_code_unique" ON "partners" USING btree ("referral_code");--> statement-breakpoint
CREATE UNIQUE INDEX "partners_email_unique" ON "partners" USING btree ("email");--> statement-breakpoint
CREATE INDEX "partners_user_idx" ON "partners" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "partners_status_idx" ON "partners" USING btree ("status");--> statement-breakpoint
CREATE INDEX "payouts_partner_idx" ON "payouts" USING btree ("partner_id");--> statement-breakpoint
CREATE UNIQUE INDEX "payouts_idempotency_key_unique" ON "payouts" USING btree ("idempotency_key");--> statement-breakpoint
CREATE INDEX "referral_clicks_partner_idx" ON "referral_clicks" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "referral_clicks_code_idx" ON "referral_clicks" USING btree ("code");--> statement-breakpoint
CREATE INDEX "referral_clicks_date_idx" ON "referral_clicks" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "referral_clicks_fp_idx" ON "referral_clicks" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "referral_events_partner_idx" ON "referral_events" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "referral_events_link_idx" ON "referral_events" USING btree ("link_id");--> statement-breakpoint
CREATE INDEX "referral_events_type_idx" ON "referral_events" USING btree ("event_type");--> statement-breakpoint
CREATE INDEX "referral_events_date_idx" ON "referral_events" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "referral_links_partner_idx" ON "referral_links" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "referral_links_code_idx" ON "referral_links" USING btree ("code");--> statement-breakpoint
CREATE INDEX "ad_events_ad_idx" ON "ad_events" USING btree ("ad_id");--> statement-breakpoint
CREATE INDEX "ad_events_type_idx" ON "ad_events" USING btree ("event_type");--> statement-breakpoint
CREATE INDEX "ad_events_date_idx" ON "ad_events" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "ad_events_campaign_idx" ON "ad_events" USING btree ("campaign_id");--> statement-breakpoint
CREATE INDEX "ad_placements_location_idx" ON "ad_placements" USING btree ("location");--> statement-breakpoint
CREATE INDEX "ad_placements_active_idx" ON "ad_placements" USING btree ("active");--> statement-breakpoint
CREATE INDEX "ad_placements_partner_idx" ON "ad_placements" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "ad_placements_campaign_idx" ON "ad_placements" USING btree ("campaign_id");--> statement-breakpoint
CREATE INDEX "campaigns_status_idx" ON "campaigns" USING btree ("status");--> statement-breakpoint
CREATE INDEX "campaigns_partner_idx" ON "campaigns" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "campaigns_type_idx" ON "campaigns" USING btree ("type");--> statement-breakpoint
CREATE INDEX "content_labels_news_idx" ON "content_labels" USING btree ("news_id");--> statement-breakpoint
CREATE INDEX "content_labels_type_idx" ON "content_labels" USING btree ("label_type");--> statement-breakpoint
CREATE INDEX "content_labels_partner_idx" ON "content_labels" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "content_labels_campaign_idx" ON "content_labels" USING btree ("campaign_id");--> statement-breakpoint
CREATE INDEX "content_labels_active_idx" ON "content_labels" USING btree ("active");--> statement-breakpoint
CREATE INDEX "monetization_events_type_idx" ON "monetization_events" USING btree ("event_type");--> statement-breakpoint
CREATE INDEX "monetization_events_article_idx" ON "monetization_events" USING btree ("article_id");--> statement-breakpoint
CREATE INDEX "monetization_events_partner_idx" ON "monetization_events" USING btree ("partner_id");--> statement-breakpoint
CREATE INDEX "monetization_events_campaign_idx" ON "monetization_events" USING btree ("campaign_id");--> statement-breakpoint
CREATE INDEX "monetization_events_date_idx" ON "monetization_events" USING btree ("created_at");